version: "3.8"

services:
  pokedb:
    image: postgres:12.10-alpine
    command: postgres -c 'max_connections=10000'
    container_name: pokepostgres
    environment:
      - POSTGRES_DB=pokeservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    networks:
      - poke_service
    volumes:
      - pke_pg_data:/var/lib/postgresql/data/

  pokeredis:
    image: redis:7.0.0-alpine
    networks:
      - poke_service
    ports:
      - "6379"
    volumes:
    - pke_redis_data:/data

  pokecode:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: pokecore
    environment:
      # SECRETS
      - SECRET_KEY=jmDT7j)kM\w<as{a_%MIB\W;&w1Ywu.sNIqX~d>XAZChAE
      - SECRET_TOKEN={sTtZLtQ2@-EzRj_\oY<,j|xWA^P&b<EPE,,lABdtPP,NzUNv6U0G[-N_k,44A4t
      # EXPIRATION SETTINGS
      - DOUBLE_FACTOR_EXPIRY_TIME_MINUTES=2
      - ACCESS_TOKEN_EXPIRE_MINUTES=28800
      - FIRST_ACCESS_TOKEN_DAY=168
      # DATABASE CONFIGURATION
      - POSTGRES_URL=postgresql+asyncpg://postgres:postgres@pokedb:5432/pokeservice
      - POSTGRES_TEST_URL=postgresql{}://postgres:postgres@pokedb:5432/
      - REDIS_HOST=pokeredis
      - REDIS_PORT=6379
      # SYSTEM SETTINGS - WARNING REMOVE THESE VARIABLES IN STG AND PRD.
      - OPEN_API_URL=/openapi.json
      - REDOC=/redoc
      - DOCS=/docs
      # URLS
      - REQUEST_ORIGIN=http://localhost:3000
      - ALLOW_ORIGINS=http://localhost:3000
      - AMBIENT_HOST=localhost:8080,0.0.0.0:8080,127.0.0.1:8080,test
      - URL_EMAIL=http://localhost:8080
      # MAIL
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_FROM=no-replay@pokeservice.com
      - MAIL_PORT=587
      - MAIL_SERVER=
      # RUNNING ENVIRONMENT
      - AMBIENT=DEV
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload --no-server-header"
    ports:
      - "8080:8080"
    networks:
      - poke_service
    depends_on:
      - pokedb
      - pokeredis
    volumes:
      - .:/code # TODO To not need remove and up all containers after code change

networks:
  poke_service:
    driver: bridge

volumes:
  pke_pg_data:
  pke_redis_data:

